name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull Docker image
      run: docker pull dovrak/playwright-1

    - name: Run Playwright tests in Docker container
      run: |
        docker run --rm \
          -v $(pwd):/workspace \
          -w /workspace \
          dovrak/playwright-1 \
          /bin/bash -c "npm ci && npx playwright install --with-deps && npx playwright test"

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
