name: Playwright Tests

on:
  push:
    branches: [main, Allure-Testing]
  pull_request:
    branches: [main, Allure-Testing]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Pull Docker image
    - name: Pull Docker image
      run: docker pull dovrak/playwright-1

    # Step 4: Run Playwright tests in Docker container
    - name: Run Playwright tests in Docker container
      run: |
        docker run --rm \
          -v $(pwd):/workspace \
          -w /workspace \
          dovrak/playwright-1 \
          /bin/bash -c "npm ci && npx playwright install --with-deps && npx playwright test"

    # Step 5: Generate Allure report
    - name: Generate Allure report
      run: allure generate --single-file ./allure-results --clean

    # Step 6: Upload Allure Report as artifact
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
